version: '3'
services:
  admin:
    container_name: dynamodb-admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    ports:
      - '8000:8000'
volumes:
  dynamodata:
    external: true